#  By default service type is ClusterIP which is internal service type
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6732
      targetPort: 6732