# By default service type is ClusterIP which is internal service type
apiVersion: v1
kind: Service
metadata:
  name: voting-result-service
spec:
  type: NodePort
  selector:
    app: voting-result
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008