apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-result-deployment
  labels:
    app: voting-result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-result
  template:
    metadata:
      labels:
        app: voting-result
    spec:
      containers:
      - name: voting-result
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80
